// Automation Awesomeness — Joe Colantonio
// 260 actionable affirmations to improve your QA and automation testing skills

export const QA_QUOTES = [
  { text: "I write tests before I write code, because quality is built in, not bolted on.", author: "Joe Colantonio" },
  { text: "I understand that flaky tests are technical debt that must be paid — with interest.", author: "Joe Colantonio" },
  { text: "I know that a test that always passes is not a test — it's a false sense of security.", author: "Joe Colantonio" },
  { text: "I embrace failure in my tests because it means I found a bug before the user did.", author: "Joe Colantonio" },
  { text: "I treat my test code with the same care and craftsmanship as my production code.", author: "Joe Colantonio" },
  { text: "I know that automation cannot replace exploratory testing — they work together.", author: "Joe Colantonio" },
  { text: "I continuously improve my test suite, removing tests that no longer add value.", author: "Joe Colantonio" },
  { text: "I use the testing pyramid as a guide: more unit tests, fewer E2E tests.", author: "Joe Colantonio" },
  { text: "I understand that speed and reliability in testing are not mutually exclusive.", author: "Joe Colantonio" },
  { text: "I make my tests independent — each test owns its setup and teardown.", author: "Joe Colantonio" },
  { text: "I know that the best bug is the one caught before it reaches production.", author: "Joe Colantonio" },
  { text: "I invest in learning new tools, but I master the fundamentals first.", author: "Joe Colantonio" },
  { text: "I communicate test results clearly, because silence is not a quality strategy.", author: "Joe Colantonio" },
  { text: "I shift testing left — quality begins at requirement, not at the end of the sprint.", author: "Joe Colantonio" },
  { text: "I own quality. It is not the QA team's job — it is everyone's responsibility.", author: "Joe Colantonio" },
  { text: "I know that a good test name is documentation that never goes out of date.", author: "Joe Colantonio" },
  { text: "I make tests readable. If I cannot explain what a test does, it is too complex.", author: "Joe Colantonio" },
  { text: "I know that CI/CD without quality gates is just fast delivery of broken software.", author: "Joe Colantonio" },
  { text: "I measure what matters: coverage, reliability, and time to feedback.", author: "Joe Colantonio" },
  { text: "I advocate for the user in every sprint, every review, every test case I write.", author: "Joe Colantonio" },
  { text: "I know that automation is a skill, and like any skill, it requires deliberate practice.", author: "Joe Colantonio" },
  { text: "I pair with developers. Testing is a team sport, not a gatekeeping function.", author: "Joe Colantonio" },
  { text: "I know that a test environment that differs from production is a risk, not a safety net.", author: "Joe Colantonio" },
  { text: "I use data-driven tests to cover more ground with less duplication.", author: "Joe Colantonio" },
  { text: "I keep my test suite fast. Slow tests are ignored tests.", author: "Joe Colantonio" },
  { text: "I understand API testing is the foundation of a solid automation strategy.", author: "Joe Colantonio" },
  { text: "I celebrate when tests catch bugs, not when all tests pass.", author: "Joe Colantonio" },
  { text: "I know that monitoring in production is testing too — it never truly ends.", author: "Joe Colantonio" },
  { text: "I continuously ask: 'What is the riskiest part of this feature?' That is what I test first.", author: "Joe Colantonio" },
  { text: "I build confidence through testing, not just coverage metrics.", author: "Joe Colantonio" },
];
